export const IAM_PERMISSION_CODES = [
  'content:read',
  'content:write',
  'content:export',
  'content:publish',
  'content:refresh',
  'packages:read',
  'packages:write',
  'packages:export',
  'packages:refresh',
  'campaigns:read',
  'campaigns:write',
  'campaigns:export',
  'campaigns:publish',
  'community:read',
  'community:write',
  'community:export',
  'tasks:read',
  'tasks:write',
  'tasks:manage',
  'tasks:export',
  'tasks:publish',
  'tasks:execute',
  'merchant:read',
  'merchant:manage',
  'analytics:read',
  'analytics:export',
  'analytics:refresh',
  'attribution:read',
  'attribution:manage',
  'jobs:read',
  'jobs:manage',
  'system:read',
  'system:manage',
  'users:read',
  'users:write',
  'users:roles',
  'iam:user:read',
  'iam:user:create',
  'iam:user:update',
  'iam:user:disable',
  'iam:access:assign',
  'iam:role:read',
  'iam:role:manage',
  'iam:org:manage',
  'iam:root',
  'iam:permissions:read',
  'iam:roles:read',
  'iam:roles:write',
  'iam:org:read',
  'iam:org:write',
  'iam:users:access',
  'audit:read',
  'audit:export'
] as const;

export type IamPermissionCode = (typeof IAM_PERMISSION_CODES)[number];

export const SYSTEM_ROLE_CODES = [
  'platform_operator',
  'area_operator',
  'merchant_operator',
  'auditor',
  'executor',
  'admin'
] as const;

export type SystemRoleCode = (typeof SYSTEM_ROLE_CODES)[number];
