<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import ErrorAlert from '../components/ErrorAlert.vue';
import { canManageOrders as resolveCanManageOrders } from '../features/write-action-permissions';
import { activateCard, freezeCard, listCardBatchOptions, listCards, redeemCard, type RedemptionCard } from '../services/api/gap-center.api';
import { buildBusinessIntentKey } from '../services/idempotency-key';
import { useRoleStore } from '../stores/role';

const roleStore = useRoleStore();
const canManageOrders = computed(() => resolveCanManageOrders(roleStore.effectiveRoles, roleStore.permissions));
const loading = ref(false); const saving = ref(false); const error = ref<string | null>(null); const items = ref<RedemptionCard[]>([]); const batches = ref<Array<{ batchId: string; batchNo: string; name: string }>>([]); const search = ref(''); const status = ref(''); const batchId = ref(''); const redeemVisible = ref(false); const redeemForm = reactive({ cardNo: '', secret: '', memberId: '', orderId: '' });
function statusLabel(value: string) { return ({ unused: '未激活', active: '可兑换', frozen: '已冻结', redeemed: '已兑换', expired: '已过期' } as Record<string, string>)[value] || value; }
function statusType(value: string) { return value === 'redeemed' ? 'success' : value === 'frozen' || value === 'expired' ? 'danger' : value === 'active' ? 'primary' : 'info'; }
function date(value: string | null) { return value ? new Date(value).toLocaleString('zh-CN') : '—'; }
async function reload() { loading.value = true; error.value = null; try { const [cardData, batchData] = await Promise.all([listCards({ search: search.value.trim() || undefined, status: status.value || undefined, batchId: batchId.value || undefined, page: 1, pageSize: 100 }), listCardBatchOptions()]); items.value = cardData.items; batches.value = batchData; } catch (cause) { error.value = cause instanceof Error ? cause.message : '卡密列表加载失败'; } finally { loading.value = false; } }
async function changeStatus(row: RedemptionCard, action: 'activate' | 'freeze') { if (!canManageOrders.value) return; saving.value = true; try { if (action === 'activate') await activateCard(row.cardId, buildBusinessIntentKey('card-batch', row.cardId, 'activate', Date.now())); else await freezeCard(row.cardId, buildBusinessIntentKey('card-batch', row.cardId, 'freeze', Date.now())); ElMessage.success(action === 'activate' ? '卡密已激活' : '卡密已冻结'); await reload(); } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '卡密状态更新失败'); } finally { saving.value = false; } }
function openRedeem() { if (!canManageOrders.value) return; Object.assign(redeemForm, { cardNo: '', secret: '', memberId: '', orderId: '' }); redeemVisible.value = true; }
async function submitRedeem() { if (!canManageOrders.value) return; if (!redeemForm.cardNo.trim() || !redeemForm.secret.trim()) { ElMessage.warning('请输入卡号和明文卡密'); return; } saving.value = true; try { await redeemCard({ ...redeemForm, cardNo: redeemForm.cardNo.trim(), secret: redeemForm.secret.trim(), memberId: redeemForm.memberId || undefined, orderId: redeemForm.orderId || undefined }, buildBusinessIntentKey('card-redeem', redeemForm.cardNo.trim(), Date.now())); ElMessage.success('卡券兑换成功'); redeemVisible.value = false; await reload(); } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '卡券兑换失败'); } finally { saving.value = false; } }
onMounted(() => void reload());
</script>

<template>
  <section v-loading="loading" class="page-stack gap-page"><div class="page-toolbar"><el-button :loading="loading" @click="reload">刷新</el-button><el-button v-if="canManageOrders" type="primary" @click="openRedeem">登记兑换</el-button></div><ErrorAlert :message="error" /><section class="panel"><div class="section-heading"><div><p class="eyebrow">REDEMPTION CARDS</p><h2>卡密列表</h2></div><span class="section-meta">{{ items.length }} 条</span></div><div class="gap-toolbar"><el-input v-model="search" clearable placeholder="搜索卡号" @keyup.enter="reload" /><el-select v-model="batchId" clearable filterable placeholder="所属批次" @change="reload"><el-option v-for="batch in batches" :key="batch.batchId" :label="`${batch.name} · ${batch.batchNo}`" :value="batch.batchId" /></el-select><el-select v-model="status" clearable placeholder="状态" @change="reload"><el-option v-for="value in ['unused','active','frozen','redeemed','expired']" :key="value" :label="statusLabel(value)" :value="value" /></el-select><el-button type="primary" @click="reload">查询</el-button></div><el-table :data="items" row-key="cardId"><el-table-column label="卡号" min-width="180"><template #default="{ row }"><strong>{{ row.cardNo }}</strong><small class="muted">密钥尾号 {{ row.secretHint }}</small></template></el-table-column><el-table-column label="批次" min-width="170"><template #default="{ row }">{{ row.batchName || '—' }}<small class="muted">{{ row.batchNo || row.batchId }}</small></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag size="small" effect="plain" :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="兑换关联" min-width="180"><template #default="{ row }">{{ row.memberId || '未关联用户' }}<small class="muted">{{ row.redeemedOrderId || '未关联订单' }}</small></template></el-table-column><el-table-column label="有效期" width="150"><template #default="{ row }">{{ date(row.validEndAt) }}</template></el-table-column><el-table-column v-if="canManageOrders" label="操作" width="180"><template #default="{ row }"><el-button v-if="['unused','frozen'].includes(row.status)" text size="small" :loading="saving" @click="changeStatus(row, 'activate')">激活</el-button><el-button v-if="['unused','active'].includes(row.status)" text size="small" type="warning" :loading="saving" @click="changeStatus(row, 'freeze')">冻结</el-button></template></el-table-column></el-table><el-empty v-if="!loading && !items.length" description="暂无卡密，请先生成卡券批次" /></section></section>
  <el-dialog v-if="canManageOrders" v-model="redeemVisible" title="登记卡券兑换" width="520px"><el-form label-position="top"><el-form-item label="卡号" required><el-input v-model="redeemForm.cardNo" /></el-form-item><el-form-item label="明文卡密" required><el-input v-model="redeemForm.secret" show-password /></el-form-item><div class="form-grid"><el-form-item label="用户 ID"><el-input v-model="redeemForm.memberId" /></el-form-item><el-form-item label="订单 ID"><el-input v-model="redeemForm.orderId" /></el-form-item></div></el-form><template #footer><el-button @click="redeemVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitRedeem">确认兑换</el-button></template></el-dialog>
</template>

<style scoped>
.gap-page{min-width:0}.gap-actions,.gap-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.gap-toolbar{margin:16px 0}.gap-toolbar .el-input{width:220px;max-width:100%}.section-heading{display:flex;justify-content:space-between;align-items:flex-start}.section-heading h2{margin:4px 0 0}.section-meta,.muted{color:var(--muted);font-size:12px}.muted{display:block;margin-top:4px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:760px){.form-grid{grid-template-columns:1fr}}
</style>
