<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import ErrorAlert from '../components/ErrorAlert.vue';
import { addMerchantLeadFollow, createMerchantLead, getMerchantLead, listMerchantLeads, updateMerchantLeadStage, type MerchantLead } from '../services/api/gap-center.api';
import { buildBusinessIntentKey } from '../services/idempotency-key';
import { canManageMerchants as resolveCanManageMerchants } from '../features/write-action-permissions';
import { useRoleStore } from '../stores/role';

const stages = [
  { value: 'potential', label: '潜在线索' }, { value: 'first_contact', label: '首次接触' }, { value: 'interested', label: '明确意向' },
  { value: 'negotiating', label: '商务洽谈' }, { value: 'submitted', label: '已提交' }, { value: 'reviewing', label: '审核中' }, { value: 'onboarded', label: '已入驻' }
];
const route = useRoute(); const router = useRouter(); const roleStore = useRoleStore();
const canManageMerchants = computed(() => resolveCanManageMerchants(roleStore.effectiveRoles, roleStore.permissions));
const loading = ref(false); const saving = ref(false); const error = ref<string | null>(null); const items = ref<MerchantLead[]>([]); const search = ref(''); const createVisible = ref(false); const selected = ref<MerchantLead | null>(null); const detailLoading = ref(false); const followContent = ref(''); const followType = ref('note');
const form = reactive({ name: '', contactName: '', contactPhone: '', regionName: '', categoryName: '', source: '', stage: 'potential' });
const grouped = computed(() => stages.map((stage) => ({ ...stage, items: items.value.filter((item) => item.stage === stage.value) })));
function stageLabel(value: string) { return stages.find((stage) => stage.value === value)?.label || value; }
function date(value: string | null) { return value ? new Date(value).toLocaleString('zh-CN') : '未安排'; }
function resetForm() { Object.assign(form, { name: '', contactName: '', contactPhone: '', regionName: '', categoryName: '', source: '', stage: 'potential' }); }
async function reload() { loading.value = true; error.value = null; try { const result = await listMerchantLeads({ search: search.value.trim() || undefined, page: 1, pageSize: 100 }); items.value = result.items; } catch (cause) { error.value = cause instanceof Error ? cause.message : 'CRM 线索加载失败'; } finally { loading.value = false; } }
async function loadDetail(id: string) { detailLoading.value = true; try { selected.value = await getMerchantLead(id); } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '线索详情加载失败'); } finally { detailLoading.value = false; } }
function openCreate() { if (!canManageMerchants.value) return; resetForm(); createVisible.value = true; }
async function submitCreate() { if (!canManageMerchants.value) return; if (!form.name.trim() || !form.contactName.trim() || !form.contactPhone.trim()) { ElMessage.warning('请填写企业名称、联系人和联系电话'); return; } saving.value = true; try { const lead = await createMerchantLead({ ...form, name: form.name.trim(), contactName: form.contactName.trim(), contactPhone: form.contactPhone.trim(), regionName: form.regionName || undefined, categoryName: form.categoryName || undefined, source: form.source || undefined }, buildBusinessIntentKey('crm-lead', form.name.trim(), Date.now())); ElMessage.success('线索已创建'); createVisible.value = false; await reload(); await router.push(`/crm/leads/${lead.leadId}`); } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '线索创建失败'); } finally { saving.value = false; } }
async function moveLead(row: MerchantLead, stage: string) { if (!canManageMerchants.value || row.stage === stage) return; try { await updateMerchantLeadStage(row.leadId, stage, buildBusinessIntentKey('crm-lead', row.leadId, stage, Date.now())); row.stage = stage; ElMessage.success('线索阶段已更新'); if (selected.value?.leadId === row.leadId) await loadDetail(row.leadId); } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '线索阶段更新失败'); } }
function handleStageChange(row: MerchantLead, value: unknown) { if (!canManageMerchants.value) return; void moveLead(row, String(value)); }
function onDragStart(row: MerchantLead, event: DragEvent) { if (!canManageMerchants.value) return; event.dataTransfer?.setData('leadId', row.leadId); }
function onDrop(stage: string, event: DragEvent) { if (!canManageMerchants.value) return; const id = event.dataTransfer?.getData('leadId'); const row = items.value.find((item) => item.leadId === id); if (row) void moveLead(row, stage); }
function openLead(row: MerchantLead) { void router.push(`/crm/leads/${row.leadId}`); }
function closeDetail() { selected.value = null; void router.push('/crm/leads'); }
async function submitFollow() { if (!canManageMerchants.value) return; if (!selected.value || !followContent.value.trim()) { ElMessage.warning('请输入跟进内容'); return; } saving.value = true; try { selected.value = await addMerchantLeadFollow(selected.value.leadId, { content: followContent.value.trim(), contactType: followType.value }, buildBusinessIntentKey('crm-lead', selected.value.leadId, 'follow', Date.now())); followContent.value = ''; ElMessage.success('跟进记录已添加'); await reload(); } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '跟进记录添加失败'); } finally { saving.value = false; } }
watch(() => route.params.leadId, (id) => { if (typeof id === 'string' && id) void loadDetail(id); else selected.value = null; }, { immediate: true });
onMounted(() => void reload());
</script>

<template>
  <section v-loading="loading" class="page-stack gap-page"><div class="page-toolbar"><el-button :loading="loading" @click="reload">刷新</el-button><el-button v-if="canManageMerchants" type="primary" @click="openCreate">新建线索</el-button></div><ErrorAlert :message="error" /><section class="panel"><div class="gap-toolbar"><el-input v-model="search" clearable placeholder="搜索企业、联系人或线索编号" @keyup.enter="reload" /><el-button type="primary" @click="reload">查询</el-button></div><div class="crm-board"><article v-for="column in grouped" :key="column.value" class="crm-column" @dragover.prevent @drop="onDrop(column.value, $event)"><div class="crm-column__head"><strong>{{ column.label }}</strong><span>{{ column.items.length }}</span></div><div v-for="row in column.items" :key="row.leadId" class="crm-card" :draggable="canManageMerchants" @dragstart="onDragStart(row, $event)" @click="openLead(row)"><strong>{{ row.name }}</strong><span>{{ row.contactName }} · {{ row.contactPhone }}</span><small>{{ row.regionName || '未填写区域' }} · {{ row.source || '来源未填写' }}</small><el-select :model-value="row.stage" size="small" :disabled="!canManageMerchants" @click.stop @change="handleStageChange(row, $event)"><el-option v-for="stage in stages" :key="stage.value" :label="stage.label" :value="stage.value" /></el-select></div><el-empty v-if="!column.items.length" :image-size="42" description="暂无" /></article></div></section>
    <el-dialog v-if="canManageMerchants" v-model="createVisible" title="新建招商线索" width="560px" :close-on-click-modal="false"><el-form label-position="top"><el-form-item label="企业名称" required><el-input v-model="form.name" /></el-form-item><div class="form-grid"><el-form-item label="联系人" required><el-input v-model="form.contactName" /></el-form-item><el-form-item label="联系电话" required><el-input v-model="form.contactPhone" /></el-form-item></div><div class="form-grid"><el-form-item label="区域"><el-input v-model="form.regionName" /></el-form-item><el-form-item label="经营品类"><el-input v-model="form.categoryName" /></el-form-item></div><div class="form-grid"><el-form-item label="来源"><el-input v-model="form.source" /></el-form-item><el-form-item label="初始阶段"><el-select v-model="form.stage" style="width:100%"><el-option v-for="stage in stages" :key="stage.value" :label="stage.label" :value="stage.value" /></el-select></el-form-item></div></el-form><template #footer><el-button @click="createVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitCreate">创建</el-button></template></el-dialog>
    <el-dialog :model-value="Boolean(selected)" title="线索详情" width="650px" @close="closeDetail"><div v-if="selected" v-loading="detailLoading" class="lead-detail"><div class="lead-detail__header"><div><p class="eyebrow">{{ selected.leadNo }}</p><h2>{{ selected.name }}</h2><p>{{ selected.contactName }} · {{ selected.contactPhone }}</p></div><el-tag effect="plain">{{ stageLabel(selected.stage) }}</el-tag></div><div class="lead-meta"><span>区域：{{ selected.regionName || '未填写' }}</span><span>品类：{{ selected.categoryName || '未填写' }}</span><span>来源：{{ selected.source || '未填写' }}</span><span>下次跟进：{{ date(selected.nextFollowAt) }}</span></div><h3>跟进时间线</h3><div class="follow-list"><div v-for="follow in selected.followRecords || []" :key="follow.followId" class="follow-row"><el-tag size="small" effect="plain">{{ follow.contactType }}</el-tag><div><p>{{ follow.content }}</p><small>{{ date(follow.createdAt) }}</small></div></div><el-empty v-if="!selected.followRecords?.length" :image-size="52" description="暂无跟进记录" /></div><div class="follow-form"><el-select v-model="followType" :disabled="!canManageMerchants" style="width:110px"><el-option label="备注" value="note" /><el-option label="电话" value="phone" /><el-option label="拜访" value="visit" /><el-option label="消息" value="message" /></el-select><el-input v-model="followContent" type="textarea" :rows="2" placeholder="记录本次跟进" :disabled="!canManageMerchants" /><el-button type="primary" :loading="saving" :disabled="!canManageMerchants" @click="submitFollow">添加跟进</el-button></div></div></el-dialog>
  </section>
</template>

<style scoped>
.gap-page{min-width:0}.gap-actions,.gap-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.gap-toolbar{margin-bottom:16px}.gap-toolbar .el-input{width:320px;max-width:100%}.crm-board{display:grid;grid-template-columns:repeat(7,minmax(170px,1fr));gap:10px;overflow-x:auto;align-items:start}.crm-column{min-height:260px;padding:10px;border-radius:10px;background:var(--soft)}.crm-column__head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.crm-column__head span{color:var(--muted);font-size:12px}.crm-card{display:grid;gap:6px;padding:11px;margin-bottom:8px;border:1px solid var(--line);border-radius:9px;background:var(--panel);cursor:pointer}.crm-card strong{font-size:13px}.crm-card span,.crm-card small{color:var(--muted);font-size:11px}.crm-card .el-select{width:100%}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.lead-detail__header{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.lead-detail__header h2{margin:4px 0}.lead-meta{display:flex;gap:12px;flex-wrap:wrap;margin:18px 0;padding:12px;border-radius:8px;background:var(--soft);color:var(--muted);font-size:12px}.lead-detail h3{margin:16px 0 8px}.follow-list{max-height:250px;overflow:auto}.follow-row{display:flex;gap:10px;padding:10px 0;border-bottom:1px solid var(--line)}.follow-row p{margin:0 0 4px;white-space:pre-wrap}.follow-row small{color:var(--muted)}.follow-form{display:grid;grid-template-columns:110px 1fr auto;gap:8px;align-items:start;margin-top:16px}@media(max-width:900px){.crm-board{grid-template-columns:repeat(7,180px)}}@media(max-width:600px){.form-grid,.follow-form{grid-template-columns:1fr}}
</style>
