<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import ErrorAlert from '../components/ErrorAlert.vue';
import { bulkShipDeliveries, createDelivery, listDeliveries, updateDelivery, type DeliveryItem } from '../services/api/gap-center.api';
import { buildBusinessIntentKey } from '../services/idempotency-key';

const loading = ref(false); const saving = ref(false); const error = ref<string | null>(null); const items = ref<DeliveryItem[]>([]); const selected = ref<DeliveryItem[]>([]); const search = ref(''); const status = ref(''); const createVisible = ref(false); const editVisible = ref(false); const form = reactive({ orderId: '', receiverName: '', receiverMobile: '', address: '' }); const edit = reactive({ deliveryId: '', logisticsCompany: '', trackingNo: '', status: 'pending', exceptionReason: '' });
function handleSelectionChange(rows: DeliveryItem[]) { selected.value = rows; }
function canSelectDelivery(row: DeliveryItem) { return ['pending', 'exception'].includes(row.status); }
function statusLabel(value: string) { return ({ pending: '待发货', shipped: '已发货', delivered: '已签收', exception: '异常', cancelled: '已取消' } as Record<string, string>)[value] || value; }
function statusType(value: string) { return value === 'exception' ? 'danger' : value === 'delivered' ? 'success' : value === 'shipped' ? 'primary' : 'info'; }
function date(value: string | null) { return value ? new Date(value).toLocaleString('zh-CN') : '—'; }
async function reload() { loading.value = true; error.value = null; try { const result = await listDeliveries({ search: search.value.trim() || undefined, status: status.value || undefined, page: 1, pageSize: 100 }); items.value = result.items; } catch (cause) { error.value = cause instanceof Error ? cause.message : '物流列表加载失败'; } finally { loading.value = false; } }
function openCreate() { Object.assign(form, { orderId: '', receiverName: '', receiverMobile: '', address: '' }); createVisible.value = true; }
async function submitCreate() { if (!form.orderId.trim()) { ElMessage.warning('请输入订单 ID'); return; } saving.value = true; try { await createDelivery({ ...form, orderId: form.orderId.trim(), receiverName: form.receiverName || undefined, receiverMobile: form.receiverMobile || undefined, address: form.address || undefined }, buildBusinessIntentKey('delivery', form.orderId.trim(), Date.now())); ElMessage.success('物流单已创建'); createVisible.value = false; await reload(); } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '物流单创建失败'); } finally { saving.value = false; } }
function openEdit(row: DeliveryItem) { Object.assign(edit, { deliveryId: row.deliveryId, logisticsCompany: row.logisticsCompany || '', trackingNo: row.trackingNo || '', status: row.status, exceptionReason: row.exceptionReason || '' }); editVisible.value = true; }
async function submitEdit() { saving.value = true; try { await updateDelivery(edit.deliveryId, { logisticsCompany: edit.logisticsCompany || undefined, trackingNo: edit.trackingNo || undefined, status: edit.status, exceptionReason: edit.exceptionReason || undefined }, buildBusinessIntentKey('delivery', edit.deliveryId, edit.status, Date.now())); ElMessage.success('物流状态已更新'); editVisible.value = false; await reload(); } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '物流单更新失败'); } finally { saving.value = false; } }
async function bulkShip() { if (!selected.value.length) { ElMessage.warning('请先选择待发货物流单'); return; } const company = window.prompt('承运商名称', '顺丰'); const trackingPrefix = window.prompt('请输入运单号前缀', 'TEST'); if (!company || !trackingPrefix) return; saving.value = true; try { await bulkShipDeliveries(selected.value.map((row, index) => ({ deliveryId: row.deliveryId, logisticsCompany: company, trackingNo: `${trackingPrefix}-${Date.now()}-${index + 1}` })), buildBusinessIntentKey('delivery', 'bulk-ship', Date.now())); ElMessage.success('批量发货已完成'); selected.value = []; await reload(); } catch (cause) { ElMessage.error(cause instanceof Error ? cause.message : '批量发货失败'); } finally { saving.value = false; } }
onMounted(() => void reload());
</script>

<template>
  <section v-loading="loading" class="page-stack gap-page"><div class="panel gap-hero"><div><p class="eyebrow">V2.0 / DELIVERY OPERATIONS</p><h1>发货物流</h1><p class="hero-description">维护订单物流单、承运商、运单号和异常状态，支持批量发货。</p></div><div class="gap-actions"><el-button :loading="loading" @click="reload">刷新</el-button><el-button :disabled="!selected.length" :loading="saving" @click="bulkShip">批量发货</el-button><el-button type="primary" @click="openCreate">新建物流单</el-button></div></div><ErrorAlert :message="error" /><section class="panel"><div class="section-heading"><div><p class="eyebrow">FULFILLMENT QUEUE</p><h2>物流单列表</h2></div><span class="section-meta">{{ items.length }} 条</span></div><div class="gap-toolbar"><el-input v-model="search" clearable placeholder="搜索物流单、订单或运单号" @keyup.enter="reload" /><el-select v-model="status" clearable placeholder="状态" @change="reload"><el-option v-for="option in [{value:'pending',label:'待发货'},{value:'shipped',label:'已发货'},{value:'delivered',label:'已签收'},{value:'exception',label:'异常'}]" :key="option.value" :label="option.label" :value="option.value" /></el-select><el-button type="primary" @click="reload">查询</el-button></div><el-table :data="items" row-key="deliveryId" @selection-change="handleSelectionChange"><el-table-column type="selection" width="45" :selectable="canSelectDelivery" /><el-table-column label="物流单" min-width="180"><template #default="{ row }"><strong>{{ row.deliveryNo }}</strong><small class="muted">{{ row.orderCode || row.orderId }}</small></template></el-table-column><el-table-column label="商家" width="150"><template #default="{ row }">{{ row.merchantName || '未关联' }}</template></el-table-column><el-table-column label="收货信息" min-width="210"><template #default="{ row }">{{ row.receiverName || '未填写' }} {{ row.receiverMobile || '' }}<small class="muted">{{ row.address || '地址未填写' }}</small></template></el-table-column><el-table-column label="承运商 / 运单" min-width="170"><template #default="{ row }">{{ row.logisticsCompany || '未填写' }}<small class="muted">{{ row.trackingNo || '未填写' }}</small></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag size="small" effect="plain" :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="更新时间" width="160"><template #default="{ row }">{{ date(row.updatedAt) }}</template></el-table-column><el-table-column label="操作" width="85"><template #default="{ row }"><el-button text size="small" @click="openEdit(row)">编辑</el-button></template></el-table-column></el-table><el-empty v-if="!loading && !items.length" description="暂无物流单，请从订单创建" /></section>
    <el-dialog v-model="createVisible" title="新建物流单" width="520px"><el-form label-position="top"><el-form-item label="订单 ID" required><el-input v-model="form.orderId" placeholder="必须是已存在的订单 ID" /></el-form-item><div class="form-grid"><el-form-item label="收货人"><el-input v-model="form.receiverName" /></el-form-item><el-form-item label="联系电话"><el-input v-model="form.receiverMobile" /></el-form-item></div><el-form-item label="收货地址"><el-input v-model="form.address" /></el-form-item></el-form><template #footer><el-button @click="createVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitCreate">创建</el-button></template></el-dialog>
    <el-dialog v-model="editVisible" title="更新物流单" width="520px"><el-form label-position="top"><div class="form-grid"><el-form-item label="承运商"><el-input v-model="edit.logisticsCompany" /></el-form-item><el-form-item label="运单号"><el-input v-model="edit.trackingNo" /></el-form-item></div><el-form-item label="状态"><el-select v-model="edit.status" style="width:100%"><el-option v-for="option in [{value:'pending',label:'待发货'},{value:'shipped',label:'已发货'},{value:'delivered',label:'已签收'},{value:'exception',label:'异常'},{value:'cancelled',label:'已取消'}]" :key="option.value" :label="option.label" :value="option.value" /></el-select></el-form-item><el-form-item v-if="edit.status === 'exception'" label="异常原因"><el-input v-model="edit.exceptionReason" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="editVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitEdit">保存</el-button></template></el-dialog>
  </section>
</template>

<style scoped>
.gap-page{min-width:0}.gap-hero{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.gap-hero h1{margin:8px 0}.gap-actions,.gap-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.gap-toolbar{margin:16px 0}.gap-toolbar .el-input{width:300px;max-width:100%}.section-heading{display:flex;justify-content:space-between;align-items:flex-start}.section-heading h2{margin:4px 0 0}.section-meta,.muted{color:var(--muted);font-size:12px}.muted{display:block;margin-top:4px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:760px){.gap-hero{flex-direction:column}.form-grid{grid-template-columns:1fr}}
</style>
